var _version=2,objScroll=new Scroll,objPerformance=new Performance,objPing=new Ping,objMeta=new Meta,objTools=new Tools,nowtime=Math.floor(new Date/1E3),tmpInt=Number(String(Math.random()).slice(2)),hit_id=Number(String(nowtime+tmpInt).slice(0,9)),objEvents=new Events;window.onload=function(){objTools.hashchangeHandler()};document.addEventListener("DOMContentLoaded",objScroll.setPageHight);document.addEventListener("scroll",objScroll.scroll);
window.addEventListener("hashchange",objTools.hashchangeHandler,!1);
function Scroll(){function c(c){for(var f=0;c;)f+=parseFloat(c.offsetTop),c=c.offsetParent;return Math.round(f)}var q=this,C=0,m=0,v=[10,20,30,40,50,60,70,80,90,100],e=v.length,R=null,G=0;this.scrollResult=0;this.setPageHight=function(){C=q.getPageHight()};this.getPageHight=function(){var e=Math.max(document.body&&document.body.scrollHeight?document.body.scrollHeight:0,document.documentElement&&document.documentElement.scrollHeight?document.documentElement.scrollHeight:0,document.body&&document.body.offsetHeight?
document.body.offsetHeight:0,document.documentElement&&document.documentElement.offsetHeight?document.documentElement.offsetHeight:0,document.body&&document.body.clientHeight?document.body.clientHeight:0,document.documentElement&&document.documentElement.clientHeight?document.documentElement.clientHeight:0),f,p=0;if(window.jQuery){var u=$("div.mia-analytics");$("div").is(".mia-analytics")&&(f=u.offset().top,u=u.outerHeight(),p=Math.round(f+u))}else(p=H("mia-analytics"))&&p[0]&&"object"==typeof p&&
(p=p[0],f=c(p),u=p.clientHeight),p=f+u;return(f=p)&&10<f?f:e};this.scroll=function(){m=window.pageYOffset||document.documentElement.scrollTop;m+=window.innerHeight;if(0<C){var c=Math.ceil(100/(C/m));c>G&&(G=c,clearTimeout(R),R=setTimeout(E,100))}};this.longArticle=function(){var c=this.getPageHight(),c=Math.floor((c-100)/window.innerHeight);0>c&&(c=0);return c};this.visualization=function(){console.log("Analytics GO");var D=document.getElementById("analytics-scala");D&&"object"==typeof D&&D.parentNode.removeChild(D);
D=H("mia-analytics")[0];if(!D||"object"!=typeof D&&10>=D.offsetHeight)D=document.body;console.log("Canvas GO");var f=document.createElement("canvas"),p=f.getContext("2d"),u=c(D);console.log("TOP",u);f.height=D.offsetHeight+35;f.width=document.body.offsetWidth;f.id="analytics-scala";f.style.position="absolute";f.style.top=u+"px";f.style.zIndex="9999";document.body.appendChild(f);p.strokeStyle="#ff0000";p.fillStyle="#ff0000";p.font="bold 30pt Arial";p.moveTo(0,1);p.lineTo(f.width,0);p.fillText("0%",
0,35);p.stroke();for(u=0;u<e;u++){var m=Math.ceil(v[u]/100*D.offsetHeight);p.moveTo(0,m);p.lineTo(f.width,m);p.fillText(v[u]+"%",0,m+35);p.stroke()}};var E=function(){var c=0;if(q.getPageHight()!=C)return q.setPageHight(),!1;if(G>q.scrollResult)for(var f=0;f<=e;f++)if(G>=v[f])c=v[f];else break;0<c&&(q.scrollResult=c)},H=function(c){var f=[];if(document.getElementsByClassName)f=document.getElementsByClassName(c);else{var e=document.body.getElementsByTagName("div"),m=e.length,f=[],H;for(H=0;H<m;H+=
1)-1!=e[H].className.search("\\b"+c+"\\b")&&f.push(e[H])}return f}}
function Performance(){this.params={navigation_type:0,timing_full_response:0,timing_dns:0,timing_download:0,timing_waiting:0,timing_request:0};this.getParams=function(){performance&&"object"==typeof performance&&performance.timing&&(this.params={navigation_type:performance.navigation.type?performance.navigation.type:255,timing_full_response:performance.timing.responseEnd-performance.timing.navigationStart,timing_dns:performance.timing.domainLookupEnd-performance.timing.domainLookupStart,timing_download:performance.timing.responseEnd-
performance.timing.responseStart,timing_waiting:performance.timing.responseStart-performance.timing.requestStart,timing_request:performance.timing.requestStart-performance.timing.connectEnd});return this.params}}
function Events(){this.request={idsite:"",url:"",_id:"",_idts:"",localtime:Math.round((new Date).getTime()/1E3),h_id:hit_id,r:"",events:[]};this.setRequestVar=function(c,q){if("events"==c)return console.log("[Events] Variable Events reserved"),!1;this.request[c]=q;return!0};this.addEvent=function(c,q){if(!c)return console.log("[Events] The event is not added, name empty!"),!1;if("object"!=typeof q)return console.log("[Events] The event is not added, params must be an object!"),!1;q.etype=c;this.request.events.push(q);
return!0};this.getReguest=function(){this.request.r=String(Math.random()).slice(2,8);var c=JSON.parse(JSON.stringify(this.request));this.request.events=[];return c}}function Tools(){this.serialize=function(c,q){var C=[],m;for(m in c)if(c.hasOwnProperty(m)){var v=q?q+"["+m+"]":m,e=c[m];C.push("object"==typeof e?this.serialize(e,v):v+"="+e)}return C.join("&")};this.hashchangeHandler=function(){var c=window.location.hash;c&&(c=c.split("#"),c[1]&&"analytics"==c[1]&&objScroll.visualization())}}
function Ping(){this.timeoutActivityStage=60;this.lastActivity=Math.floor(new Date/1E3);this.activityStage=1;this.getCurrentNum=function(){var c=Math.floor(new Date/1E3);c-this.lastActivity>this.timeoutActivityStage&&255>this.activityStage&&this.activityStage++;this.lastActivity=c;return this.activityStage}}
function Meta(){document.querySelectorAll(".ab__testing-info");this.getMeta=function(){var c=[],q=document.getElementsByTagName("meta"),C;for(C in q){var m=q[C];"object"==typeof m&&m.getAttribute("property")&&-1<m.getAttribute("property").indexOf("analytics:")&&(c[m.getAttribute("property").split(":")[1]]=m.getAttribute("content"))}return c}}"object"!==typeof JSON2&&(JSON2={});
(function(){function c(c){return 10>c?"0"+c:c}function q(c){v.lastIndex=0;return v.test(c)?'"'+c.replace(v,function(c){var f=G[c];return"string"===typeof f?f:"\\u"+("0000"+c.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+c+'"'}function C(m,D){var f,p,u,v,G=e,N,t=D[m];t&&"object"===typeof t&&(f=t,u=Object.prototype.toString.apply(f),t="[object Date]"===u?isFinite(f.valueOf())?f.getUTCFullYear()+"-"+c(f.getUTCMonth()+1)+"-"+c(f.getUTCDate())+"T"+c(f.getUTCHours())+":"+c(f.getUTCMinutes())+":"+c(f.getUTCSeconds())+
"Z":null:"[object String]"===u||"[object Number]"===u||"[object Boolean]"===u?f.valueOf():"[object Array]"!==u&&"function"===typeof f.toJSON?f.toJSON(m):f);"function"===typeof E&&(t=E.call(D,m,t));switch(typeof t){case "string":return q(t);case "number":return isFinite(t)?String(t):"null";case "boolean":case "null":return String(t);case "object":if(!t)return"null";e+=R;N=[];if("[object Array]"===Object.prototype.toString.apply(t)){v=t.length;for(f=0;f<v;f+=1)N[f]=C(f,t)||"null";u=0===N.length?"[]":
e?"[\n"+e+N.join(",\n"+e)+"\n"+G+"]":"["+N.join(",")+"]";e=G;return u}if(E&&"object"===typeof E)for(v=E.length,f=0;f<v;f+=1)"string"===typeof E[f]&&(p=E[f],(u=C(p,t))&&N.push(q(p)+(e?": ":":")+u));else for(p in t)Object.prototype.hasOwnProperty.call(t,p)&&(u=C(p,t))&&N.push(q(p)+(e?": ":":")+u);u=0===N.length?"{}":e?"{\n"+e+N.join(",\n"+e)+"\n"+G+"}":"{"+N.join(",")+"}";e=G;return u}}var m=RegExp("[\x00\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]",
"g"),v=RegExp('[\\\\\\"\x00-\u001f\u007f-\u009f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]',"g"),e,R,G={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},E;"function"!==typeof JSON2.stringify&&(JSON2.stringify=function(c,m,f){var p;R=e="";if("number"===typeof f)for(p=0;p<f;p+=1)R+=" ";else"string"===typeof f&&(R=f);if((E=m)&&"function"!==typeof m&&("object"!==typeof m||"number"!==typeof m.length))throw Error("JSON2.stringify");
return C("",{"":c})});"function"!==typeof JSON2.parse&&(JSON2.parse=function(c,e){function f(c,m){var p,q,t=c[m];if(t&&"object"===typeof t)for(p in t)Object.prototype.hasOwnProperty.call(t,p)&&(q=f(t,p),void 0!==q?t[p]=q:delete t[p]);return e.call(c,m,t)}var p;c=String(c);m.lastIndex=0;m.test(c)&&(c=c.replace(m,function(c){return"\\u"+("0000"+c.charCodeAt(0).toString(16)).slice(-4)}));if(/^[\],:{}\s]*$/.test(c.replace(RegExp('\\\\(?:["\\\\/bfnrt]|u[0-9a-fA-F]{4})',"g"),"@").replace(RegExp('"[^"\\\\\n\r]*"|true|false|null|-?\\d+(?:\\.\\d*)?(?:[eE][+\\-]?\\d+)?',
"g"),"]").replace(RegExp("(?:^|:|,)(?:\\s*\\[)+","g"),"")))return p=eval("("+c+")"),"function"===typeof e?f({"":p},""):p;throw new SyntaxError("JSON2.parse");})})();"object"!==typeof _paq&&(_paq=[]);
"object"!==typeof Piwik&&(Piwik=function(){function c(a){return"undefined"!==typeof a}function q(a){return"function"===typeof a}function C(a){return"object"===typeof a}function m(a){return"string"===typeof a||a instanceof String}function v(){var a,b,g;for(a=0;a<arguments.length;a+=1)g=arguments[a],b=g.shift(),m(b)?S[b].apply(S,g):b.apply(S,g)}function e(a,b,g,d){if(a.addEventListener)return a.addEventListener(b,g,d),!0;if(a.attachEvent)return a.attachEvent("on"+b,g);a["on"+b]=g}function R(a,b){var g=
"",d,c;for(d in la)Object.prototype.hasOwnProperty.call(la,d)&&(c=la[d][a],q(c)&&(g+=c(b)));return g}function G(){var a;if(!ma)for(ma=!0,R("load"),a=0;a<Ka.length;a++)Ka[a]();return!0}function E(a,b){var c=n.createElement("script");c.type="text/javascript";c.src=a;c.readyState?c.onreadystatechange=function(){var a=this.readyState;if("loaded"===a||"complete"===a)c.onreadystatechange=null,b()}:c.onload=b;n.getElementsByTagName("head")[0].appendChild(c)}function H(){var a="";try{a=h.top.document.referrer}catch(b){if(h.parent)try{a=
h.parent.document.referrer}catch(c){a=""}}""===a&&(a=n.referrer);return a}function D(a){return(a=/^([a-z]+):/.exec(a))?a[1]:null}function f(a){var b=/^(?:(?:https?|ftp):)\/*(?:[^@]+@)?([^:/#]+)/.exec(a);return b?b[1]:a}function p(a,b){var c=(new RegExp("[\\?&#]"+b+"=([^&#]*)")).exec(a);return c?ib(c[1]):""}function u(a){var b=function(a,b){return a<<b|a>>>32-b},c=function(a){var b="",c,d;for(c=7;0<=c;c--)d=a>>>4*c&15,b+=d.toString(16);return b},d,f,e=[],n=1732584193,l=4023233417,h=2562383102,m=271733878,
p=3285377520,x,k,q,u,t,v=[];a=jb(A(a));x=a.length;for(d=0;d<x-3;d+=4)f=a.charCodeAt(d)<<24|a.charCodeAt(d+1)<<16|a.charCodeAt(d+2)<<8|a.charCodeAt(d+3),v.push(f);switch(x&3){case 0:d=2147483648;break;case 1:d=a.charCodeAt(x-1)<<24|8388608;break;case 2:d=a.charCodeAt(x-2)<<24|a.charCodeAt(x-1)<<16|32768;break;case 3:d=a.charCodeAt(x-3)<<24|a.charCodeAt(x-2)<<16|a.charCodeAt(x-1)<<8|128}for(v.push(d);14!==(v.length&15);)v.push(0);v.push(x>>>29);v.push(x<<3&4294967295);for(a=0;a<v.length;a+=16){for(d=
0;16>d;d++)e[d]=v[a+d];for(d=16;79>=d;d++)e[d]=b(e[d-3]^e[d-8]^e[d-14]^e[d-16],1);f=n;x=l;k=h;q=m;u=p;for(d=0;19>=d;d++)t=b(f,5)+(x&k|~x&q)+u+e[d]+1518500249&4294967295,u=q,q=k,k=b(x,30),x=f,f=t;for(d=20;39>=d;d++)t=b(f,5)+(x^k^q)+u+e[d]+1859775393&4294967295,u=q,q=k,k=b(x,30),x=f,f=t;for(d=40;59>=d;d++)t=b(f,5)+(x&k|x&q|k&q)+u+e[d]+2400959708&4294967295,u=q,q=k,k=b(x,30),x=f,f=t;for(d=60;79>=d;d++)t=b(f,5)+(x^k^q)+u+e[d]+3395469782&4294967295,u=q,q=k,k=b(x,30),x=f,f=t;n=n+f&4294967295;l=l+x&4294967295;
h=h+k&4294967295;m=m+q&4294967295;p=p+u&4294967295}t=c(n)+c(l)+c(h)+c(m)+c(p);return t.toLowerCase()}function Wb(a,b,c){if("translate.googleusercontent.com"===a)""===c&&(c=b),b=p(b,"u"),a=f(b);else if("cc.bingj.com"===a||"webcache.googleusercontent.com"===a||"74.6."===a.slice(0,5))b=n.links[0].href,a=f(b);return[a,b,c]}function Ja(a){var b=a.length;"."===a.charAt(--b)&&(a=a.slice(0,b));"*."===a.slice(0,2)&&(a=a.slice(1));return a}function N(a){a=a&&a.text?a.text:a;if(!m(a)){var b=n.getElementsByTagName("title");
b&&c(b[0])&&(a=b[0].text)}return a}function t(a){return a?!c(a.children)&&c(a.childNodes)||c(a.children)?a.children:[]:[]}function Z(a,b){if(a&&a.indexOf)return a.indexOf(b);if(!c(a)||null===a||!a.length)return-1;var g=a.length;if(0===g)return-1;for(var d=0;d<g;){if(a[d]===b)return d;d++}return-1}function kb(a){function b(a,b){if(h.getComputedStyle)return n.defaultView.getComputedStyle(a,null)[b];if(a.currentStyle)return a.currentStyle[b]}function g(d,f,e,l,h,m,p){var k=d.parentNode,q;a:{for(q=d.parentNode;q;){if(q===
n){q=!0;break a}q=q.parentNode}q=!1}if(!q)return!1;if(9===k.nodeType)return!0;if("0"===b(d,"opacity")||"none"===b(d,"display")||"hidden"===b(d,"visibility"))return!1;c(f)&&c(e)&&c(l)&&c(h)&&c(m)&&c(p)||(f=d.offsetTop,h=d.offsetLeft,l=f+d.offsetHeight,e=h+d.offsetWidth,m=d.offsetWidth,p=d.offsetHeight);if(a===d&&(0===p||0===m)&&"hidden"===b(d,"overflow"))return!1;if(k){if("hidden"===b(k,"overflow")||"scroll"===b(k,"overflow"))if(h+1>k.offsetWidth+k.scrollLeft||h+m-1<k.scrollLeft||f+1>k.offsetHeight+
k.scrollTop||f+p-1<k.scrollTop)return!1;d.offsetParent===k&&(h+=k.offsetLeft,f+=k.offsetTop);return g(k,f,e,l,h,m,p)}return!0}return a?g(a):!1}function Ma(a,b){if(b)return b;"piwik.php"===a.slice(-9)&&(a=a.slice(0,a.length-9));return a}function da(a){var b=/index\.php\?module=Overlay&action=startOverlaySession&idSite=([0-9]+)&period=([^&]+)&date=([^&]+)$/.exec(n.referrer);if(b){if(b[1]!==String(a))return!1;h.name="Piwik_Overlay###"+b[2]+"###"+b[3]}a=h.name.split("###");return 3===a.length&&"Piwik_Overlay"===
a[0]}function Yb(a,b,c){var d=h.name.split("###"),f=d[1],e=d[2],l=Ma(a,b);E(l+"plugins/Overlay/client/client.js?v=1",function(){Piwik_Overlay_Client.initialize(l,c,f,e)})}function oa(a,b,g){function d(y,a,w,b,c,d){if(!aa){var g;w&&(g=new Date,g.setTime(g.getTime()+w));n.cookie=y+"="+A(a)+(w?";expires="+g.toGMTString():"")+";path="+(b||"/")+(c?";domain="+c:"")+(d?";secure":"")}}function t(y){return aa?0:(y=(new RegExp("(^|;)[ ]*"+y+"=([^;]*)")).exec(n.cookie))?ib(y[2]):0}function v(y){var a;return lb?
(a=/#.*/,y.replace(a,"")):y}function G(y){var a,w,b;for(a=0;a<xa.length;a++){w=Ja(xa[a].toLowerCase());if(y===w)return!0;if("."===w.slice(0,1)){if(y===w.slice(1))return!0;b=y.length-w.length;if(0<b&&y.slice(b)===w)return!0}}return!1}function E(y,a){var w=new Image(1,1);w.onload=function(){F=0;"function"===typeof a&&a()};w.src=L+(0>L.indexOf("?")?"?":"&")+y}function S(y,a,w){var b=new Image(1,1);b.onload=function(){F=0;"function"===typeof w&&w()};b.src=a+(0>L.indexOf("?")?"?":"&")+y}function Z(y,a,
w){c(w)&&null!==w||(w=!0);try{var b=h.XMLHttpRequest?new h.XMLHttpRequest:h.ActiveXObject?new ActiveXObject("Microsoft.XMLHTTP"):null;b.open("POST",L,!0);b.onreadystatechange=function(){4!==this.readyState||200<=this.status&&300>this.status||!w?"function"===typeof a&&a():E(y,a)};b.setRequestHeader("Content-Type",mb);b.send(y)}catch(d){w&&E(y,a)}}function T(y){y=(new Date).getTime()+y;if(!pa||y>pa)pa=y}function x(y){var a=(new Date).getTime();ea&&a<ea?(a=ea-a,setTimeout(y,a),T(a+50),ea+=50):(!1===
ea&&(ea=a+800),y())}function I(y,a,b){!ya&&y&&x(function(){"POST"===nb?Z(y,b):E(y,b);T(a)})}function wa(a,r){var b;b=ya?!1:a&&a.length;if(b){var c='{"requests":["?'+a.join('","?')+'"]}';x(function(){Z(c,null,!1);T(r)})}}function U(a){return ob+a+"."+V+"."+pb}function va(){if(aa)return"0";if(!c(B.cookieEnabled)){var a=U("testcookie");d(a,"1");return"1"===t(a)?"1":"0"}return B.cookieEnabled?"1":"0"}function ga(){pb=qb((W||Oa)+(X||"/")).slice(0,4)}function La(){var a=U("cvar"),a=t(a);return a.length&&
(a=JSON2.parse(a),C(a))?a:{}}function K(){Pa=(new Date).getTime()}function O(){Qa=!0}function na(){var a=new Date,r=Math.round(a.getTime()/1E3),b=t(U("id"));b?(a=b.split("."),a.unshift("0")):(Ra||(Ra=qb((B.userAgent||"")+(B.platform||"")+JSON2.stringify(Y)+a.getTime()+Math.random()).slice(0,16)),a=["1",Ra,r,0,r,"",""]);return a}function oa(){var a=(new Date).getTime(),r=na();return 1E3*parseInt(r[2],10)+Sa-a}function Ma(a,r,b,c,g,f){var e=oa();d(U("id"),a+"."+r+"."+b+"."+c+"."+g+"."+f,e,X,W)}function ha(){var a=
t(U("ref"));if(a.length)try{if(a=JSON2.parse(a),C(a))return a}catch(r){}return["","",0,""]}function rb(){var a=aa;aa=!1;d(U("id"),"",-86400,X,W);d(U("ses"),"",-86400,X,W);d(U("cvar"),"",-86400,X,W);d(U("ref"),"",-86400,X,W);aa=a}function sb(a){if(a&&C(a)){var r=[],b;for(b in a)Object.prototype.hasOwnProperty.call(a,b)&&r.push(b);b={};r.sort();var c=r.length,d;for(d=0;d<c;d++)b[r[d]]=a[r[d]];return b}}function M(a,r,b,g){function e(a,y){var r=JSON2.stringify(a);return 2<r.length?"&"+y+"="+A(r):""}
var h,l=new Date,m=Math.round(l.getTime()/1E3),k,u,x,C,D,E,z,J,B,H,K=Q,O=U("ses"),F=U("ref"),P=U("cvar");z=na();H=t(O);B=ha();var N=qa||Ta,I,L;aa&&rb();if(ya)return"";k=z[0];u=z[1];C=z[2];x=z[3];D=z[4];E=z[5];c(z[6])||(z[6]="");z=z[6];c(g)||(g="");var M=n.characterSet||n.charset;M&&"utf-8"!==M.toLowerCase()||(M=null);I=B[0];L=B[1];J=B[2];B=B[3];var T;if(H)T=JSON2.parse(H);else{H=za/1E3;if(!E||m-E>H)x++,E=D;if(!Ua||!I.length){for(h in Aa)if(Object.prototype.hasOwnProperty.call(Aa,h)&&(I=p(N,Aa[h]),
I.length))break;for(h in Ba)if(Object.prototype.hasOwnProperty.call(Ba,h)&&(L=p(N,Ba[h]),L.length))break}D=f(ia);H=B.length?f(B):"";!D.length||G(D)||Ua&&H.length&&!G(H)||(B=ia);if(B.length||I.length)J=m,B=[I,L,J,v(B.slice(0,1024))],d(F,JSON2.stringify(B),tb,X,W);a+="&new_session=1"}l.getMonth();F=objPerformance.getParams();a+="&idsite="+V+"&rec=1&r="+String(Math.random()).slice(2,8)+"&ltime="+Math.round(l.getTime()/1E3)+"&url="+A(v(N))+(ia.length?"&urlref="+A(v(ia).substr(0,1E3)):"")+(Ca.length?"&uid="+
A(Ca):"")+"&_id="+u+"&_idts="+C+"&_idvc="+x+"&_idn="+k+(I.length?"&_rcn="+A(I):"")+(L.length?"&_rck="+A(L):"")+"&_refts="+J+"&_viewts="+E+(String(z).length?"&_ects="+z:"")+(M?"&cs="+A(M):"")+"&s_img=0&mdata="+ub+"&n_tp="+F.navigation_type+"&t_fl_r="+F.timing_full_response+"&t_dns="+F.timing_dns+"&t_dw="+F.timing_download+"&t_wt="+F.timing_waiting+"&t_rq="+F.timing_request+"&ver="+_version+"&h_id="+hit_id+"&l_arc="+objScroll.longArticle();if((l=objMeta.getMeta())&&"object"==typeof l)var S=objTools.serialize(l,
"meta");S&&(a+="&"+S);for(h in Y)Object.prototype.hasOwnProperty.call(Y,h)&&(a+="&"+h+"="+Y[h]);r?a+="&data="+A(JSON2.stringify(r)):ba&&(a+="&data="+A(JSON2.stringify(ba)));r=sb(fa);S=sb(Va);a+=e(r,"cvar");a+=e(S,"e_cvar");if(Q){a+=e(Q,"_cvar");for(h in K)Object.prototype.hasOwnProperty.call(K,h)&&(""!==Q[h][0]&&""!==Q[h][1]||delete Q[h]);vb&&d(P,JSON2.stringify(Q),za,X,W)}wb&&(Wa?a+="&gt_ms="+Wa:ja&&ja.timing&&ja.timing.requestStart&&ja.timing.responseEnd&&(a+="&gt_ms="+(ja.timing.responseEnd-ja.timing.requestStart)));
h=$b(T);K={depth:h};Ma(u,C,x,m,E,c(g)&&String(g).length?g:z);d(O,JSON2.stringify(K),za,X,W);a=a+("&depth="+h)+R(b);Xa.length&&(a+="&"+Xa);q(Ya)&&(a=Ya(a));return a}function $b(a){var r=0;a&&(r=a.depth);a=f(ia);var b=f(location.hostname);return a&&a==b?r+1:r}function xb(a,r,b,d,g,f){var e="idgoal=0",h,l=new Date,m=[],k;String(a).length&&(e+="&ec_id="+A(a),h=Math.round(l.getTime()/1E3));e+="&revenue="+r;String(b).length&&(e+="&ec_st="+b);String(d).length&&(e+="&ec_tx="+d);String(g).length&&(e+="&ec_sh="+
g);String(f).length&&(e+="&ec_dt="+f);if(J){for(k in J)Object.prototype.hasOwnProperty.call(J,k)&&(c(J[k][1])||(J[k][1]=""),c(J[k][2])||(J[k][2]=""),c(J[k][3])&&0!==String(J[k][3]).length||(J[k][3]=0),c(J[k][4])&&0!==String(J[k][4]).length||(J[k][4]=1),m.push(J[k]));e+="&ec_items="+A(JSON2.stringify(m))}e=M(e,ba,"ecommerce",h);I(e,z)}function ac(a,r){var b=new Date,c=a||yb,c=c.substr(0,500),c=M("action_name="+A(N(c)),r,"log");I(c,z);Za&&ra&&!zb&&(zb=!0,e(n,"click",K),e(n,"mouseup",K),e(n,"mousedown",
K),e(n,"mousemove",K),e(n,"mousewheel",K),e(h,"DOMMouseScroll",K),e(h,"scroll",K),e(n,"keypress",K),e(n,"keydown",K),e(n,"keyup",K),e(h,"resize",K),e(h,"focus",K),e(h,"blur",K),Pa=b.getTime(),setTimeout(function Na(){var a;b=new Date;Pa+ra>b.getTime()&&(Za<b.getTime()&&(a=M("ping=1",r,"ping"),I(a,z)),setTimeout(Na,ra))},ra))}function $a(a,r){var b,c="(^| )(piwik[_-]"+r;if(a)for(b=0;b<a.length;b++)c+="|"+a[b];return new RegExp(c+")( |$)")}function sa(a){return L&&a&&0===String(a).indexOf(L)}function ab(a){var r=
a;for(a=r.parentNode;null!==a&&c(a)&&!l.isLinkElement(r);)r=a,a=r.parentNode;a=r;if(l.hasNodeAttribute(a,"href")&&c(a.href)&&(r=l.getAttributeValueFromNode(a,"href"),!sa(r))){var r=a.hostname||f(a.href),b=r.toLowerCase(),r=a.href.replace(r,b);if(!/^(javascript|vbscript|jscript|mocha|livescript|ecmascript|mailto):/i.test(r)){a=a.className;b=G(b);if(sa(r))a=0;else{var d=$a(Ab,"download"),g=$a(Bb,"link"),e=new RegExp("\\.("+ta+")([?&#]|$)","i");a=g.test(a)?"link":d.test(a)||e.test(r)?"download":b?0:
"link"}if(a)return{type:a,href:r}}}}function ua(a,b,w,c){if(a=k.buildInteractionRequestParams(a,b,w,c))return M(a,null,"contentInteraction")}function Cb(a,b,w,d,g){if(c(a)){if(sa(a))return a;var e=k.toAbsoluteUrl(a),e="redirecturl="+A(e)+"&",e=e+ua(b,w,d,g||a);a="&";0>L.indexOf("?")&&(a="?");return L+a+e}}function bb(a,b){if(!a||!b)return!1;var w=k.findTargetNode(a);if(k.shouldIgnoreInteraction(w))return!1;var w=k.findTargetNodeNoDefault(a),c;if(c=w)c=!(w&&b&&(w.contains?w.contains(b):w===b||w.compareDocumentPosition&&
w.compareDocumentPosition(b)&16));return c?!1:!0}function Db(a,b,w){if(a){var c=k.findParentContentNode(a);if(c&&bb(c,a)&&(a=k.buildContentBlock(c)))return!a.target&&w&&(a.target=w),k.buildInteractionRequestParams(b,a.name,a.piece,a.target)}}function Eb(a){if(!ca||!ca.length)return!1;var b,c;for(b=0;b<ca.length;b++)if((c=ca[b])&&c.name===a.name&&c.piece===a.piece&&c.target===a.target)return!0;return!1}function cb(a){if(!a)return!1;var b=k.findTargetNode(a);if(!b||k.shouldIgnoreInteraction(b))return!1;
var c=ab(b);if(db&&c&&c.type)return!1;if(l.isLinkElement(b)&&l.hasNodeAttributeWithValue(b,"href")){c=String(l.getAttributeValueFromNode(b,"href"));if(0===c.indexOf("#"))return!1;if(sa(c))return!0;if(!k.isUrlToCurrentDomain(c))return!1;var d=k.buildContentBlock(a);if(!d)return;a=d.name;var g=d.piece,d=d.target;if(!l.hasNodeAttributeWithValue(b,k.CONTENT_TARGET_ATTR)||b.wasContentTargetAttrReplaced)b.wasContentTargetAttrReplaced=!0,d=k.toAbsoluteUrl(c),l.setAnyAttribute(b,k.CONTENT_TARGET_ATTR,d);
c=Cb(c,"click",a,g,d);k.setHrefAttribute(b,c);return!0}return!1}function Fb(a){return function(b){if(a){var c=k.findParentContentNode(a),d;b&&(d=b.target||b.srcElement);d||(d=a);if(bb(c,d)){T(z);l.isLinkElement(a)&&l.hasNodeAttributeWithValue(a,"href")&&l.hasNodeAttributeWithValue(a,k.CONTENT_TARGET_ATTR)&&(b=l.getAttributeValueFromNode(a,"href"),!sa(b)&&a.wasContentTargetAttrReplaced&&l.setAnyAttribute(a,k.CONTENT_TARGET_ATTR,""));b=ab(a);if(Da&&b&&b.type)return b.type;if(cb(c))return"href";if(c=
k.buildContentBlock(c))return c=ua("click",c.name,c.piece,c.target),I(c,z),c}}}}function Gb(a){if(a&&a.length){var b,c;for(b=0;b<a.length;b++)(c=k.findTargetNode(a[b]))&&!c.contentInteractionTrackingSetupDone&&(c.contentInteractionTrackingSetupDone=!0,e(c,"click",Fb(c)))}}function Hb(a,b){if(!a||!a.length)return[];var c,d;for(c=0;c<a.length;c++)Eb(a[c])?(a.splice(c,1),c--):ca.push(a[c]);if(!a||!a.length)return[];if(b&&b.length)for(c=0;c<b.length;c++)cb(b[c]);Gb(b);var g=[];for(c=0;c<a.length;c++)d=
M(k.buildImpressionRequestParams(a[c].name,a[c].piece,a[c].target),void 0,"contentImpressions"),g.push(d);return g}function Ea(a){var b=k.collectContent(a);return Hb(b,a)}function eb(a){if(!a||!a.length)return[];var b;for(b=0;b<a.length;b++)k.isNodeVisible(a[b])||(a.splice(b,1),b--);return a&&a.length?Ea(a):[]}function Ib(a,b,c){a=k.buildImpressionRequestParams(a,b,c);return M(a,null,"contentImpression")}function Jb(a,b){if(a){var c=k.findParentContentNode(a);if(c=k.buildContentBlock(c))return b||
(b="Unknown"),ua(b,c.name,c.piece,c.target)}}function Kb(a,b,d,g,e){if(0===String(a).length||0===String(b).length)return!1;a="e_c="+A(a)+"&e_a="+A(b)+(c(d)?"&e_n="+A(d):"")+(c(g)?"&e_v="+A(g):"");e=M(a,e,"event");I(e,z)}function Lb(a,b,c,d,g){b=b+"="+A(v(a));(a=Db(g,"click",a))&&(b+="&"+a);c=M(b,c,"link");I(c,d?0:z,d)}function Mb(a,b){return""!==a?a+b.charAt(0).toUpperCase()+b.slice(1):b}function P(a){var b,c,d=["","webkit","ms","moz"],g;if(!Nb)for(c=0;c<d.length;c++)if(g=d[c],Object.prototype.hasOwnProperty.call(n,
Mb(g,"hidden"))){"prerender"===n[Mb(g,"visibilityState")]&&(b=!0);break}b?e(n,g+"visibilitychange",function Zb(){n.removeEventListener(g+"visibilitychange",Zb,!1);a()}):a()}function Fa(a){"complete"===n.readyState?a():h.addEventListener?h.addEventListener("load",a):h.attachEvent&&h.attachEvent("onLoad",a)}function fb(a){var b=!1;(b=n.attachEvent?"complete"===n.readyState:"loading"!==n.readyState)?a():n.addEventListener?n.addEventListener("DOMContentLoaded",a):n.attachEvent&&n.attachEvent("onreadystatechange",
a)}function Ob(a){var b=ab(a);b&&b.type&&(b.href=jb(b.href),Lb(b.href,b.type,void 0,null,a))}function gb(a){var b,c;a=a||h.event;b=a.which||a.button;c=a.target||a.srcElement;"click"===a.type?c&&Ob(c):"mousedown"===a.type?1!==b&&2!==b||!c?Ga=Ha=null:(Ga=b,Ha=c):"mouseup"===a.type&&(b===Ga&&c===Ha&&Ob(c),Ga=Ha=null)}function Pb(a,b){b?(e(a,"mouseup",gb,!1),e(a,"mousedown",gb,!1)):e(a,"click",gb,!1)}function Qb(a){if(!Da){Da=!0;var b,c=$a(Rb,"ignore"),d=n.links;if(d)for(b=0;b<d.length;b++)c.test(d[b].className)||
Pb(d[b],a)}}function Sb(a,b,c){function d(){g=!0}if(ka)return!0;ka=!0;var g=!1,e,f;Fa(function(){function k(a){setTimeout(function(){ka&&(g=!1,c.trackVisibleContentImpressions(),k(a))},a)}function l(a){setTimeout(function(){ka&&(g&&(g=!1,c.trackVisibleContentImpressions()),l(a))},a)}if(a){e=["scroll","resize"];for(f=0;f<e.length;f++)n.addEventListener?n.addEventListener(e[f],d):h.attachEvent("on"+e[f],d);l(100)}b&&0<b&&(b=parseInt(b,10),k(b))})}var Ia={},hb=Wb(n.domain,h.location.href,H()),Oa=Ja(hb[0]),
Ta=hb[1],ia=hb[2],Tb=!1,nb="GET",mb="application/x-www-form-urlencoded; charset=UTF-8",L=a||"//a.ria.ru/counter",Ub="",Xa="",V=b||"",ub="",Ca="",qa,yb=n.title,ta="7z|aac|apk|ar[cj]|as[fx]|avi|azw3|bin|csv|deb|dmg|docx?|epub|exe|flv|gif|gz|gzip|hqx|jar|jpe?g|js|mobi|mp(2|3|4|e?g)|mov(ie)?|ms[ip]|od[bfgpst]|og[gv]|pdf|phps|png|pptx?|qtm?|ra[mr]?|rpm|sea|sit|tar|t?bz2?|tgz|torrent|txt|wav|wm[av]|wpd||xlsx?|xml|z|zip",xa=[Oa],Rb=[],Ab=[],Bb=[],z=500,Za,ra,lb,ba,Aa=["pk_campaign","piwik_campaign","utm_campaign",
"utm_source","utm_medium"],Ba=["pk_kwd","piwik_kwd","utm_term"],ob="_pk_",W,X,aa=!1,ya,Nb,Ua,Sa=339552E5,za=18E5,tb=15768E6,wb=!0,Wa=0,vb=!1,Q=!1,Ya,fa={},Va={},J={},Y={},ca=[],ka=!1,ea=!1,Da=!1,db=!1,zb=!1,Pa,Qa=!1,Ga,Ha,qb=u,pb,Ra=g;(function(){var a,b,d={pdf:"application/pdf",qt:"video/quicktime",realp:"audio/x-pn-realaudio-plugin",wma:"application/x-mplayer2",dir:"application/x-director",fla:"application/x-shockwave-flash",java:"application/x-java-vm",gears:"application/x-googlegears",ag:"application/x-silverlight"},
g=/Mac OS X.*Safari\//.test(B.userAgent)?h.devicePixelRatio||1:1;if(!/MSIE/.test(B.userAgent)){if(B.mimeTypes&&B.mimeTypes.length)for(a in d)Object.prototype.hasOwnProperty.call(d,a)&&(b=B.mimeTypes[d[a]],Y[a]=b&&b.enabledPlugin?"1":"0");"unknown"!==typeof navigator.javaEnabled&&c(B.javaEnabled)&&B.javaEnabled()&&(Y.java="1");q(h.GearsFactory)&&(Y.gears="1");Y.cookie=va()}Y.res=Vb.width*g+"x"+Vb.height*g})();ga();R("run",function(a,b){var d=null;if(m(a)&&!c(Ia[a])&&b){if(C(b))d=b;else if(m(b))try{eval("hookObj ="+
b)}catch(g){}Ia[a]=d}return d});return{hook:Ia,getHook:function(a){return Ia[a]},getQuery:function(){return l},getContent:function(){return k},buildContentImpressionRequest:Ib,buildContentInteractionRequest:ua,buildContentInteractionRequestNode:Jb,buildContentInteractionTrackingRedirectUrl:Cb,getContentImpressionsRequestsFromNodes:Ea,getCurrentlyVisibleContentImpressionsRequestsIfNotTrackedYet:eb,trackCallbackOnLoad:Fa,trackCallbackOnReady:fb,buildContentImpressionsRequests:Hb,wasContentImpressionAlreadyTracked:Eb,
appendContentInteractionToRequestIfPossible:Db,setupInteractionsTracking:Gb,trackContentImpressionClickInteraction:Fb,internalIsNodeVisible:kb,isNodeAuthorizedToTriggerInteraction:bb,replaceHrefIfInternalLink:cb,getConfigDownloadExtensions:function(){return ta},enableTrackOnlyVisibleContent:function(a,b){return Sb(a,b,this)},clearTrackedContentImpressions:function(){ca=[]},getTrackedContentImpressions:function(){return ca},getTrackerUrl:function(){return L},clearEnableTrackOnlyVisibleContent:function(){ka=
!1},disableLinkTracking:function(){db=Da=!1},getConfigVisitorCookieTimeout:function(){return Sa},getRemainingVisitorCookieTimeout:oa,getVisitorId:function(){return na()[1]},getVisitorInfo:function(){return na()},getAttributionInfo:function(){return ha()},getAttributionCampaignName:function(){return ha()[0]},getAttributionCampaignKeyword:function(){return ha()[1]},getAttributionReferrerTimestamp:function(){return ha()[2]},getAttributionReferrerUrl:function(){return ha()[3]},setTrackerUrl:function(a){L=
a},setSiteId:function(a){V=a},setMetadata:function(a){ub=a},setUserId:function(a){Ca=a},getUserId:function(){return Ca},setCustomData:function(a,b){C(a)?ba=a:(ba||(ba={}),ba[a]=b)},getCustomData:function(){return ba},setCustomRequestProcessing:function(a){Ya=a},appendToTrackingUrl:function(a){Xa=a},getRequest:function(a){return M(a)},addPlugin:function(a,b){la[a]=b},setCustomVariable:function(a,b,d,g){c(g)||(g="visit");c(b)&&(c(d)||(d=""),0<a&&(b=m(b)?b:String(b),d=m(d)?d:String(d),b=[b.slice(0,200),
d.slice(0,200)],"visit"===g||2===g?(!1===Q&&(Q=La()),Q[a]=b):"page"===g||3===g?fa[a]=b:"event"===g&&(Va[a]=b)))},getCustomVariable:function(a,b){var d;c(b)||(b="visit");if("page"===b||3===b)d=fa[a];else if("event"===b)d=Va[a];else if("visit"===b||2===b)!1===Q&&(Q=La()),d=Q[a];return!c(d)||d&&""===d[0]?!1:d},deleteCustomVariable:function(a,b){this.getCustomVariable(a,b)&&this.setCustomVariable(a,"","",b)},storeCustomVariablesInCookie:function(){vb=!0},setLinkTrackingTimer:function(a){z=a},setDownloadExtensions:function(a){ta=
a},addDownloadExtensions:function(a){ta+="|"+a},setDomains:function(a){xa=m(a)?[a]:a;xa.push(Oa)},setIgnoreClasses:function(a){Rb=m(a)?[a]:a},setRequestMethod:function(a){nb=a||"GET"},setRequestContentType:function(a){mb=a||"application/x-www-form-urlencoded; charset=UTF-8"},setReferrerUrl:function(a){ia=a},setCustomUrl:function(a){var b=Ta,c;D(a)?qa=a:"/"===a.slice(0,1)?qa=D(b)+"://"+f(b)+a:(b=v(b),c=b.indexOf("?"),0<=c&&(b=b.slice(0,c)),c=b.lastIndexOf("/"),c!==b.length-1&&(b=b.slice(0,c+1)),qa=
b+a)},setDocumentTitle:function(a){yb=a},setAPIUrl:function(a){Ub=a},setDownloadClasses:function(a){Ab=m(a)?[a]:a},setLinkClasses:function(a){Bb=m(a)?[a]:a},setCampaignNameKey:function(a){Aa=m(a)?[a]:a},setCampaignKeywordKey:function(a){Ba=m(a)?[a]:a},discardHashTag:function(a){lb=a},setCookieNamePrefix:function(a){ob=a;Q=La()},setCookieDomain:function(a){W=Ja(a);ga()},setCookiePath:function(a){X=a;ga()},setVisitorCookieTimeout:function(a){Sa=1E3*a},setSessionCookieTimeout:function(a){za=1E3*a},setReferralCookieTimeout:function(a){tb=
1E3*a},setConversionAttributionFirstReferrer:function(a){Ua=a},disableCookies:function(){aa=!0;Y.cookie="0"},deleteCookies:function(){rb()},setDoNotTrack:function(a){var b=B.doNotTrack||B.msDoNotTrack;(ya=a&&("yes"===b||"1"===b))&&this.disableCookies()},addListener:function(a,b){Pb(a,b)},enableLinkTracking:function(a){db=!0;ma?Qb(a):Ka.push(function(){Qb(a)})},enableJSErrorTracking:function(){if(!Tb){Tb=!0;var a=h.onerror;h.onerror=function(b,c,d,g,e){P(function(){var a=c+":"+d;g&&(a+=":"+g);Kb("JavaScript Errors",
a,b)});return a?a(b,c,d,g,e):!1}}},disablePerformanceTracking:function(){wb=!1},setGenerationTimeMs:function(a){Wa=parseInt(a,10)},setHeartBeatTimer:function(a,b){Za=(new Date).getTime()+1E3*a;ra=1E3*b},killFrame:function(){h.location!==h.top.location&&(h.top.location=h.location)},redirectFile:function(a){"file:"===h.location.protocol&&(h.location=a)},setCountPreRendered:function(a){Nb=a},trackGoal:function(a,b,c){P(function(){var d=M("idgoal="+a+(b?"&revenue="+b:""),c,"goal");I(d,z)})},trackLink:function(a,
b,c,d){P(function(){Lb(a,b,c,d)})},trackPageView:function(a,b){ca=[];da(V)?P(function(){Yb(L,Ub,V)}):P(function(){ac(a,b)})},trackAllContentImpressions:function(){da(V)||P(function(){fb(function(){var a=k.findContentNodes(),a=Ea(a);wa(a,z)})})},trackVisibleContentImpressions:function(a,b){da(V)||(c(a)||(a=!0),c(b)||(b=750),Sb(a,b,this),P(function(){Fa(function(){var a=k.findContentNodes(),a=eb(a);wa(a,z)})}))},trackContentImpression:function(a,b,c){!da(V)&&a&&(b=b||"Unknown",P(function(){var d=Ib(a,
b,c);I(d,z)}))},trackContentImpressionsWithinNode:function(a){!da(V)&&a&&P(function(){ka?Fa(function(){var b=k.findContentNodesWithinNode(a),b=eb(b);wa(b,z)}):fb(function(){var b=k.findContentNodesWithinNode(a),b=Ea(b);wa(b,z)})})},trackContentInteraction:function(a,b,c,d){!da(V)&&a&&b&&(c=c||"Unknown",P(function(){var g=ua(a,b,c,d);I(g,z)}))},trackContentInteractionNode:function(a,b){!da(V)&&a&&P(function(){var c=Jb(a,b);I(c,z)})},trackEvent:function(a,b,c,d){P(function(){Kb(a,b,c,d)})},trackSiteSearch:function(a,
b,d){P(function(){var g=M("search="+A(a)+(b?"&search_cat="+A(b):"")+(c(d)?"&search_count="+d:""),void 0,"sitesearch");I(g,z)})},setEcommerceView:function(a,b,d,g){c(d)&&d.length?d instanceof Array&&(d=JSON2.stringify(d)):d="";fa[5]=["_pkc",d];c(g)&&String(g).length&&(fa[2]=["_pkp",g]);if(c(a)&&a.length||c(b)&&b.length)c(a)&&a.length&&(fa[3]=["_pks",a]),c(b)&&b.length||(b=""),fa[4]=["_pkn",b]},addEcommerceItem:function(a,b,c,d,g){a.length&&(J[a]=[a,b,c,d,g])},trackEcommerceOrder:function(a,b,d,g,e,
f){String(a).length&&c(b)&&xb(a,b,d,g,e,f)},trackEcommerceCartUpdate:function(a){c(a)&&xb("",a,"","","","")},startPing:function(a,b){a=0>=a?5E3:1E3*a;b=b||"//a.ria.ru/ping";var c=0,d=na();e(n,"click",O);e(n,"mouseup",O);e(n,"mousedown",O);e(n,"mousemove",O);e(n,"mousewheel",O);e(h,"DOMMouseScroll",O);e(h,"scroll",O);e(n,"keypress",O);e(n,"keydown",O);e(n,"keyup",O);e(h,"resize",O);e(h,"focus",O);e(h,"blur",O);objEvents.setRequestVar("idsite",V);objEvents.setRequestVar("url",A(v(qa||Ta)));objEvents.setRequestVar("_id",
d[1]);objEvents.setRequestVar("_idts",d[2]);setTimeout(function Na(){if(!0===Qa){Qa=!1;var d=objScroll.scrollResult;objEvents.addEvent("ping",{a_st:objPing.getCurrentNum()});d>c&&(objEvents.addEvent("scroll",{value_uint8:d}),c=d);d=objEvents.getReguest();d=objTools.serialize(d);S(d,b)}setTimeout(Na,a)},a)}}}var pa,la={},n=document,B=navigator,Vb=screen,h=window,ja=h.performance||h.mozPerformance||h.msPerformance||h.webkitPerformance,ma=!1,Ka=[],A=h.encodeURIComponent,ib=h.decodeURIComponent,jb=unescape,
S,F,va,l={htmlCollectionToArray:function(a){var b=[],c;if(!a||!a.length)return b;for(c=0;c<a.length;c++)b.push(a[c]);return b},find:function(a){if(!document.querySelectorAll||!a)return[];a=document.querySelectorAll(a);return this.htmlCollectionToArray(a)},findMultiple:function(a){if(!a||!a.length)return[];var b,c,d=[];for(b=0;b<a.length;b++)c=this.find(a[b]),d=d.concat(c);return d=this.makeNodesUnique(d)},findNodesByTagName:function(a,b){if(!a||!b||!a.getElementsByTagName)return[];var c=a.getElementsByTagName(b);
return this.htmlCollectionToArray(c)},makeNodesUnique:function(a){var b=[].concat(a);a.sort(function(a,c){if(a===c)return 0;var d=Z(b,a),g=Z(b,c);return d===g?0:d>g?-1:1});if(1>=a.length)return a;var c=0,d=0,e=[],f;for(f=a[c++];f;)f===a[c]&&(d=e.push(c)),f=a[c++]||null;for(;d--;)a.splice(e[d],1);return a},getAttributeValueFromNode:function(a,b){if(this.hasNodeAttribute(a,b)){if(a&&a.getAttribute)return a.getAttribute(b);if(a&&a.attributes&&"undefined"!==typeof a.attributes[b]){if(a.attributes[b].value)return a.attributes[b].value;
if(a.attributes[b].nodeValue)return a.attributes[b].nodeValue;var c,d=a.attributes;if(d){for(c=0;c<d.length;c++)if(d[c].nodeName===b)return d[c].nodeValue;return null}}}},hasNodeAttributeWithValue:function(a,b){return!!this.getAttributeValueFromNode(a,b)},hasNodeAttribute:function(a,b){return a&&a.hasAttribute?a.hasAttribute(b):a&&a.attributes?"undefined"!==typeof a.attributes[b]:!1},hasNodeCssClass:function(a,b){if(a&&b&&a.className){var c=a.className.split(" ");if(-1!==Z(c,b))return!0}return!1},
findNodesHavingAttribute:function(a,b,c){c||(c=[]);if(!a||!b)return c;a=t(a);if(!a||!a.length)return c;var d,e;for(d=0;d<a.length;d++)e=a[d],this.hasNodeAttribute(e,b)&&c.push(e),c=this.findNodesHavingAttribute(e,b,c);return c},findFirstNodeHavingAttribute:function(a,b){if(a&&b){if(this.hasNodeAttribute(a,b))return a;var c=this.findNodesHavingAttribute(a,b);if(c&&c.length)return c[0]}},findFirstNodeHavingAttributeWithValue:function(a,b){if(a&&b){if(this.hasNodeAttributeWithValue(a,b))return a;var c=
this.findNodesHavingAttribute(a,b);if(c&&c.length){var d;for(d=0;d<c.length;d++)if(this.getAttributeValueFromNode(c[d],b))return c[d]}}},findNodesHavingCssClass:function(a,b,c){c||(c=[]);if(!a||!b)return c;if(a.getElementsByClassName)return b=a.getElementsByClassName(b),this.htmlCollectionToArray(b);a=t(a);if(!a||!a.length)return[];var d,e;for(d=0;d<a.length;d++)e=a[d],this.hasNodeCssClass(e,b)&&c.push(e),c=this.findNodesHavingCssClass(e,b,c);return c},findFirstNodeHavingClass:function(a,b){if(a&&
b){if(this.hasNodeCssClass(a,b))return a;var c=this.findNodesHavingCssClass(a,b);if(c&&c.length)return c[0]}},isLinkElement:function(a){if(!a)return!1;a=String(a.nodeName).toLowerCase();return-1!==Z(["a","area"],a)},setAnyAttribute:function(a,b,c){a&&b&&(a.setAttribute?a.setAttribute(b,c):a[b]=c)}},k={CONTENT_ATTR:"data-track-content",CONTENT_CLASS:"piwikTrackContent",CONTENT_NAME_ATTR:"data-content-name",CONTENT_PIECE_ATTR:"data-content-piece",CONTENT_PIECE_CLASS:"piwikContentPiece",CONTENT_TARGET_ATTR:"data-content-target",
CONTENT_TARGET_CLASS:"piwikContentTarget",CONTENT_IGNOREINTERACTION_ATTR:"data-content-ignoreinteraction",CONTENT_IGNOREINTERACTION_CLASS:"piwikContentIgnoreInteraction",location:void 0,findContentNodes:function(){return l.findMultiple(["."+this.CONTENT_CLASS,"["+this.CONTENT_ATTR+"]"])},findContentNodesWithinNode:function(a){if(!a)return[];var b=l.findNodesHavingCssClass(a,this.CONTENT_CLASS),c=l.findNodesHavingAttribute(a,this.CONTENT_ATTR);if(c&&c.length){var d;for(d=0;d<c.length;d++)b.push(c[d])}l.hasNodeAttribute(a,
this.CONTENT_ATTR)?b.push(a):l.hasNodeCssClass(a,this.CONTENT_CLASS)&&b.push(a);return b=l.makeNodesUnique(b)},findParentContentNode:function(a){if(a)for(var b=0;a&&a!==n&&a.parentNode;){if(l.hasNodeAttribute(a,this.CONTENT_ATTR)||l.hasNodeCssClass(a,this.CONTENT_CLASS))return a;a=a.parentNode;if(1E3<b)break;b++}},findPieceNode:function(a){var b;(b=l.findFirstNodeHavingAttribute(a,this.CONTENT_PIECE_ATTR))||(b=l.findFirstNodeHavingClass(a,this.CONTENT_PIECE_CLASS));return b?b:a},findTargetNodeNoDefault:function(a){if(a){var b=
l.findFirstNodeHavingAttributeWithValue(a,this.CONTENT_TARGET_ATTR);if(b||(b=l.findFirstNodeHavingAttribute(a,this.CONTENT_TARGET_ATTR))||(b=l.findFirstNodeHavingClass(a,this.CONTENT_TARGET_CLASS)))return b}},findTargetNode:function(a){var b=this.findTargetNodeNoDefault(a);return b?b:a},findContentName:function(a){if(a){var b=l.findFirstNodeHavingAttributeWithValue(a,this.CONTENT_NAME_ATTR);if(b)return l.getAttributeValueFromNode(b,this.CONTENT_NAME_ATTR);if(b=this.findContentPiece(a))return this.removeDomainIfIsInLink(b);
if(l.hasNodeAttributeWithValue(a,"title"))return l.getAttributeValueFromNode(a,"title");b=this.findPieceNode(a);if(l.hasNodeAttributeWithValue(b,"title"))return l.getAttributeValueFromNode(b,"title");a=this.findTargetNode(a);if(l.hasNodeAttributeWithValue(a,"title"))return l.getAttributeValueFromNode(a,"title")}},findContentPiece:function(a){if(a){var b=l.findFirstNodeHavingAttributeWithValue(a,this.CONTENT_PIECE_ATTR);if(b)return l.getAttributeValueFromNode(b,this.CONTENT_PIECE_ATTR);a=this.findPieceNode(a);
if(a=this.findMediaUrlInNode(a))return this.toAbsoluteUrl(a)}},findContentTarget:function(a){if(a){var b=this.findTargetNode(a);if(l.hasNodeAttributeWithValue(b,this.CONTENT_TARGET_ATTR))return l.getAttributeValueFromNode(b,this.CONTENT_TARGET_ATTR);if(l.hasNodeAttributeWithValue(b,"href"))return a=l.getAttributeValueFromNode(b,"href"),this.toAbsoluteUrl(a);a=this.findPieceNode(a);if(l.hasNodeAttributeWithValue(a,"href"))return a=l.getAttributeValueFromNode(a,"href"),this.toAbsoluteUrl(a)}},isSameDomain:function(a){if(!a||
!a.indexOf)return!1;if(0===a.indexOf(this.getLocation().origin))return!0;a=a.indexOf(this.getLocation().host);return 8>=a&&0<=a?!0:!1},removeDomainIfIsInLink:function(a){a&&a.search&&-1!==a.search(/^https?:\/\/[^/]+/)&&this.isSameDomain(a)&&((a=a.replace(/^.*\/\/[^/]+/,""))||(a="/"));return a},findMediaUrlInNode:function(a){if(a){var b=a.nodeName.toLowerCase();if(-1!==Z(["img","embed","video","audio"],b)&&l.findFirstNodeHavingAttributeWithValue(a,"src"))return a=l.findFirstNodeHavingAttributeWithValue(a,
"src"),l.getAttributeValueFromNode(a,"src");if("object"===b&&l.hasNodeAttributeWithValue(a,"data"))return l.getAttributeValueFromNode(a,"data");if("object"===b){if((b=l.findNodesByTagName(a,"param"))&&b.length){var c;for(c=0;c<b.length;c++)if("movie"===l.getAttributeValueFromNode(b[c],"name")&&l.hasNodeAttributeWithValue(b[c],"value"))return l.getAttributeValueFromNode(b[c],"value")}if((a=l.findNodesByTagName(a,"embed"))&&a.length)return this.findMediaUrlInNode(a[0])}}},trim:function(a){return a&&
String(a)===a?a.replace(/^\s+|\s+$/g,""):a},isOrWasNodeInViewport:function(a){if(!a||!a.getBoundingClientRect||1!==a.nodeType)return!0;var b=a.getBoundingClientRect(),c=n.documentElement||{},d=0>b.top;d&&a.offsetTop&&(d=0<a.offsetTop+b.height);a=c.clientWidth;h.innerWidth&&a>h.innerWidth&&(a=h.innerWidth);c=c.clientHeight;h.innerHeight&&c>h.innerHeight&&(c=h.innerHeight);return(0<b.bottom||d)&&0<b.right&&b.left<a&&(b.top<c||d)},isNodeVisible:function(a){var b=kb(a);a=this.isOrWasNodeInViewport(a);
return b&&a},buildInteractionRequestParams:function(a,b,c,d){var e="";a&&(e+="c_i="+A(a));b&&(e&&(e+="&"),e+="c_n="+A(b));c&&(e&&(e+="&"),e+="c_p="+A(c));d&&(e&&(e+="&"),e+="c_t="+A(d));return e},buildImpressionRequestParams:function(a,b,c){a="c_n="+A(a)+"&c_p="+A(b);c&&(a+="&c_t="+A(c));return a},buildContentBlock:function(a){if(a){var b=this.findContentName(a),c=this.findContentPiece(a);a=this.findContentTarget(a);b=this.trim(b);c=this.trim(c);a=this.trim(a);return{name:b||"Unknown",piece:c||"Unknown",
target:a||""}}},collectContent:function(a){if(!a||!a.length)return[];var b=[],e,d;for(e=0;e<a.length;e++)d=this.buildContentBlock(a[e]),c(d)&&b.push(d);return b},setLocation:function(a){this.location=a},getLocation:function(){var a=this.location||h.location;a.origin||(a.origin=a.protocol+"//"+a.hostname+(a.port?":"+a.port:""));return a},toAbsoluteUrl:function(a){return a&&String(a)===a||""===a?""===a?this.getLocation().href:-1!==a.search(/^\/\//)?this.getLocation().protocol+a:-1!==a.search(/:\/\//)?
a:0===a.indexOf("#")||0===a.indexOf("?")?this.getLocation().origin+this.getLocation().pathname+a:0===a.search("^[a-zA-Z]{2,11}:")?a:-1!==a.search(/^\//)?this.getLocation().origin+a:this.getLocation().origin+this.getLocation().pathname.match(/(.*\/)/)[0]+a:a},isUrlToCurrentDomain:function(a){a=this.toAbsoluteUrl(a);if(!a)return!1;var b=this.getLocation().origin;return b===a?!0:0===String(a).indexOf(b)?":"===String(a).substr(b.length,1)?!1:!0:!1},setHrefAttribute:function(a,b){a&&b&&l.setAnyAttribute(a,
"href",b)},shouldIgnoreInteraction:function(a){var b=l.hasNodeAttribute(a,this.CONTENT_IGNOREINTERACTION_ATTR);a=l.hasNodeCssClass(a,this.CONTENT_IGNOREINTERACTION_CLASS);return b||a}};e(h,"beforeunload",function(){var a;R("unload");if(pa){do a=new Date;while(a.getTimeAlias()<pa)}},!1);(function(){var a;n.addEventListener?e(n,"DOMContentLoaded",function g(){n.removeEventListener("DOMContentLoaded",g,!1);G()}):n.attachEvent&&(n.attachEvent("onreadystatechange",function d(){"complete"===n.readyState&&
(n.detachEvent("onreadystatechange",d),G())}),n.documentElement.doScroll&&h===h.top&&function Xb(){if(!ma){try{n.documentElement.doScroll("left")}catch(a){setTimeout(Xb,0);return}G()}}());/WebKit/.test(B.userAgent)&&(a=setInterval(function(){if(ma||/loaded|complete/.test(n.readyState))clearInterval(a),G()},10));e(h,"load",G,!1)})();Date.prototype.getTimeAlias=Date.prototype.getTime;S=new oa;var ga={setTrackerUrl:1,setAPIUrl:1,setSiteId:1,disableCookies:1,enableLinkTracking:1,setMetadata:1},T;for(F=
0;F<_paq.length;F++)T=_paq[F][0],ga[T]&&(v(_paq[F]),delete _paq[F],1<ga[T]&&void 0!==console&&console&&console.error&&console.error("The method "+T+' is registered more than once in "_paq" variable. Only the last call has an effect. Please have a look at the multiple Piwik trackers documentation: http://developer.piwik.org/api-reference/tracking-javascript#multiple-piwik-trackers'),ga[T]++);for(F=0;F<_paq.length;F++)_paq[F]&&v(_paq[F]);_paq=new function(){return{push:v}};va={addPlugin:function(a,
b){la[a]=b},getTracker:function(a,b){return new oa(a,b,S.getVisitorId())},getAsyncTracker:function(){return S}};"function"===typeof define&&define.amd&&define("piwik",[],function(){return va});return va}());window&&window.piwikAsyncInit&&window.piwikAsyncInit();(function(){"undefined"===typeof AnalyticsTracker&&(AnalyticsTracker=Piwik)})();
"function"!==typeof piwik_log&&(piwik_log=function(c,q,C,m){function v(c){try{return eval("piwik_"+c)}catch(e){}}var e=Piwik.getTracker(C,q);e.setDocumentTitle(c);e.setCustomData(m);(c=v("tracker_pause"))&&e.setLinkTrackingTimer(c);(c=v("download_extensions"))&&e.setDownloadExtensions(c);(c=v("hosts_alias"))&&e.setDomains(c);(c=v("ignore_classes"))&&e.setIgnoreClasses(c);e.trackPageView();v("install_tracker")&&(piwik_track=function(c,m,q,v){e.setSiteId(m);e.setTrackerUrl(q);e.trackLink(c,v)},e.enableLinkTracking())});var _paq=_paq||[];_paq.push(["startPing",15]);
